services:
  haproxy:
    image: ha_proxy_jolokia
    build: ../haproxy
    restart: always
    ports:
      - 80:80
      - 1936:1936
    networks:
      - spring-network

  springBootAdmin:
    image: adultswim/springbootadmin
    build: ../springbootadmin
    restart: always
    ports:
      - 8080:8080
    networks:
      - spring-network

  jolokia_no_ssl_1:
    image: jolokia-jolokia_no_ssl
    build: .
    restart: always
    ports:
      - 8081:8080
      - 5001:5000
      - 5051:5001
    networks:
      - spring-network

  jolokia_no_ssl_2:
    image: jolokia-jolokia_no_ssl
    build: .
    restart: always
    ports:
      - 8082:8080
      - 5002:5000
      - 5052:5001
    networks:
      - spring-network

networks:
  spring-network: